[phases.setup]
nixPkgs = ["python311", "chromium", "chromedriver"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "python src/main.py"

[variables]
CHROME_BIN = "/nix/store/*/bin/chromium"
CHROMEDRIVER_PATH = "/nix/store/*/bin/chromedriver"

